export const FETCH_IMAGES_REQUEST = 'FETCH_IMAGES_REQUEST';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE';
export const RECEIVE_IMAGES = 'RECEIVE_IMAGES';
export const VIEW_DETAILS = 'VIEW_DETAILS';
export const CLICK_IMAGE = 'CLICK_IMAGE';
